// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetobiblioteca.Context;

#nullable disable

namespace projetobiblioteca.Migrations
{
    [DbContext(typeof(MSSQL))]
    [Migration("20260804134946_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projetobiblioteca.Data.Aluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Endereço")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("projetobiblioteca.Data.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Endereço")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Função")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("projetobiblioteca.Data.Livro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("Emprestados")
                        .HasColumnType("bigint");

                    b.Property<long>("Estoque")
                        .HasColumnType("bigint");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("livros");
                });

            modelBuilder.Entity("projetobiblioteca.Model.EmprestimoFuncionari", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Devolvido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("date");

                    b.Property<long>("IdAluno")
                        .HasColumnType("bigint");

                    b.Property<long>("IdLivro")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdLivro");

                    b.ToTable("EmprestimosAlunos");
                });

            modelBuilder.Entity("projetobiblioteca.Model.EmprestimoFuncionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Devolvido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("date");

                    b.Property<long>("IdFuncionario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdLivro")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("EmprestimosFuncionarios");
                });

            modelBuilder.Entity("projetobiblioteca.Model.EmprestimoFuncionari", b =>
                {
                    b.HasOne("projetobiblioteca.Data.Aluno", "Aluno")
                        .WithMany("EmprestimosAluno")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projetobiblioteca.Data.Livro", "Livro")
                        .WithMany("EmprestimosAluno")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("projetobiblioteca.Model.EmprestimoFuncionario", b =>
                {
                    b.HasOne("projetobiblioteca.Data.Funcionario", "Funcionario")
                        .WithMany("EmprestimoFuncionario")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projetobiblioteca.Data.Livro", "Livro")
                        .WithMany("EmprestimosFuncionario")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("projetobiblioteca.Data.Aluno", b =>
                {
                    b.Navigation("EmprestimosAluno");
                });

            modelBuilder.Entity("projetobiblioteca.Data.Funcionario", b =>
                {
                    b.Navigation("EmprestimoFuncionario");
                });

            modelBuilder.Entity("projetobiblioteca.Data.Livro", b =>
                {
                    b.Navigation("EmprestimosAluno");

                    b.Navigation("EmprestimosFuncionario");
                });
#pragma warning restore 612, 618
        }
    }
}
